config/routes.rb
Rails.application.routes.draw do

  root 'coins#index'

  resources :creators, only: [:index]

  resources :coins, only: [:index, :show]

  resources :users, except: [:index, :destroy]

  resources :following, only: [:index, :update, :destroy] do
    resources :alerts, except: [:index, :new, :show]
    get 'alert_form' => 'alerts#alert_form'
  end

  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  has_many :alerts

  validates :user_id, :coin_name, presence: true
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController

  before_action :require_login

  def index
    @user = current_user
    @following = Following.where(user_id: @user.id)
    @avatar = @user.avatar_url
    @alert = Alert.new
    @coin_summary = CoinService.summary
    @cc_coin_list = CoinService.cc_coin_list(@coin_summary)
  end

  def update
    @coin_symbol = params[:id]
    @is_following = Following.find_by(user_id: current_user.id, coin_name: @coin_symbol)
    if !@is_following
      @follow = Following.new
      @follow.user_id = current_user.id
      @follow.coin_name = params[:id]

      respond_to do |format|
        format.html
        format.json do
          if @follow.save
            render json:{}, nothing: true, status: 204
          else
            render json:{}, nothing: true, status: 400
          end
        end
      end
    end
  end

  def destroy
    @coin_symbol = params[:id]
    @follow = Following.find_by(user_id: current_user.id, coin_name: @coin_symbol)
    @alerts = @follow.alerts
    @nil_following_ids = Alert.where(following_id: nil)

    if @alerts.present?
      @alerts.delete_all # this deletes the following_id foreign key so we don't get the error "violates foreign key rule"
      @nil_following_ids.destroy_all # after the foreign key is removed, we delete the alerts with the following_id: nil
    end

    respond_to do |format|
      format.html
      format.json do
        if @follow.destroy
          render json:{}, nothing: true, status: 204
        else
          render json:{}, nothing: true, status: 400
        end
      end
    end
  end
end

# @follow.coin_name and  @coin_symbol is referring to the show page of the coin the user is currently on

app/helpers/following_helper.rb
module FollowingHelper
end

app/views/following/index.html.erb
<div class="container">
  <h1><img id="avatar" src="<%= @avatar %>" alt="avatar"><%= @user.username %>'s Portfolio</h1>

  <%= link_to "Back to Coins", root_url %>

  <div class="row">
    <% count = 0 %>
    <ul class="collapsible" data-collapsible="accordion">

      <!-- if the user portfolio is empty, display this message -->
      <% if @following.empty? %>
        <h4 class="center-align">Follow coins from their individual pages.</h4>
      <% end %>

      <!-- Iterating to display all the coins the current user is following in their portfolio -->
      <% @following.each do |follow| %>
        <!-- Iteration from Bittrex to display each follow's current price -->
        <% @coin_summary.each do |coin| %>
          <% if coin.name == "BTC-#{follow.coin_name}" %>
          <!-- Creates variables to use later in the coin portfolio -->
            <% @coin_last = coin.last_price %>
            <% @coin_volume = coin.volume %>
          <% end %>
        <% end %>
          <li>
            <div class="collapsible-header">
              <div class="col s4">
                <h4><%= image_tag("#{@cc_coin_list[follow.coin_name][:image_url]}", size: "40x40", alt: "#{@cc_coin_list[follow.coin_name][:full_name]}") %>
                <%= link_to follow.coin_name, coin_path(follow.coin_name) %>
                </h4>
              </div>
              <div class="right col s3" id="followings-price">
                Price: Ƀ
                <%= @coin_last %>
              </div>
              <div class="right col s4" id="followings-price">
                Volume:
                <%= @coin_volume %>
              </div>
              <% if follow.alerts.length > 0 %>
                <div class="right col s1">
                  <h4 id="wolf-alert" class="alert"><%= image_tag("alerts", size: "30x30") %>&nbsp;<span class="alert-count"><%= follow.alerts.count %></span></h4>
                </div>
              <% else %>
                <div class="right col s1"></div>
              <% end %>

              <div class="row">
                <div class="col s12">
                  <i class="material-icons">arrow_drop_down</i>
                </div>
              </div>
            </div>

            <div class="collapsible-body">
              <table class="bordered">
                <thead>
                  <tr>
                    <th data-sortable="false">Price above</th>
                    <th data-sortable="false">Price below</th>
                    <th data-sortable="false">24h change</th>
                    <th data-sortable="false">Status</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody class="alerts-table">
                  <!-- Display all alerts for each followed coin -->
                  <% follow.alerts.each do |alert| %>
                    <tr class="alerts-info">
                      <td><%= alert.price_above %></td>
                      <td><%= alert.price_below %></td>
                      <td><%= alert.percent %>%</td>
                      <% if alert.state == "Active" %>
                        <td>
                          <p><%= alert.state %>&nbsp;<%= image_tag("active-alert", size: "20x20") %></p>
                        </td>
                      <% elsif alert.state == "Inactive" %>
                        <td>
                          <p><%= alert.state %>&nbsp;<%= image_tag("inactive-alert", size: "20x20") %></p>
                        </td>
                      <% end %>
                      <td>
                        <a data-target="modal<%= count +=1%>" class="modal-trigger link-pointer" action="#modal<%= count %>">
                        Edit</a>

                      <!-- EDIT ALERT FORM -->
                        <div id="modal<%= count %>" class="modal">
                          <div class="modal-content">
                            <%= render 'alerts/form2', follow: follow, alert: alert, method: :put, remote: true %>
                          </div>
                        </div>
                      |
                      <%= link_to "Delete", following_alert_path(follow, alert), remote: true, method: :delete, class: 'delete_alert', data: {confirm: "Are you sure you want to delete this alert?" } %>
                      </td>
                    </tr>
                  <% end %>
                  <!-- END OF ALERT LOOP -->

                  <tr>
                  <!-- ADD ALERT TO LIST OF FOLLOWED COINS -->
                    <td colspan="6">
                      <div class="right-align">
                        <button data-target="modal<%= count +=1%>" class="btn modal-trigger cyan accent-4" action="#modal<%= count %>">
                          <i class="material-icons left">add</i>Add Alert
                        </button>
                      </div>
                    </td>
                  </tr>

                  <!-- ADD ALERT FORM -->
                  <div id="modal<%= count %>" class="modal">
                    <div class="modal-content">
                    <!-- cannot render the partial for the alert. for NEW method, it can't be @following, must be >>follow<< like in the iteration -->
                      <%= render 'alerts/form3', follow: follow, alert: @alert, method: :put, remote: true%>
                    </div>
                  </div>
                  <!-- END OF ADD ALERT MODAL -->

                </tbody>
              </table>
            </div>
          </li>
      <% end %>
      <!-- END OF FOLLOWING LOOP -->
    </ul>
  </div>
</div>