config/routes.rb
Rails.application.routes.draw do

  root 'coins#index'

  resources :creators, only: [:index]

  resources :coins, only: [:index, :show]

  resources :users, except: [:index, :destroy]

  resources :following, only: [:index, :update, :destroy] do
    resources :alerts, except: [:index, :new, :show]
    get 'alert_form' => 'alerts#alert_form'
  end

  resources :sessions, only: [:create]
  get 'login' => 'sessions#new', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    @coin_summary = CoinService.summary
    @ext_data = CoinService.ext_data(@coin_summary)
    @cc_coin_list = CoinService.cc_coin_list(@coin_summary)

    # Data needed for carousel top 5
    sorted_summary = @coin_summary.sort_by { |coin| coin.pct_change.to_i }
    @top_5_coins = sorted_summary[-5..-1].reverse
    @carousel_position = ["#one!","#two!","#three!","#four!","#five!"]
  end

  def show
    coin_symbol = params[:id]
    coin_summary = CoinService.summary
    @coin = CoinService.get_coin(coin_symbol)
    @image_url = CoinService.ext_data(coin_summary)[coin_symbol][:image_url]
    @cc_coin_list = CoinService.cc_coin_list(@coin)
    if current_user
      @following = Following.find_by(user_id: current_user.id, coin_name: coin_symbol)
      @is_following = @following.present? ? true : false
      @alert = Alert.new
    end
    if coin_symbol == 'BCC'
      @data_by_minute_result = get_chart_data_by_minute('BCH', 100)
    else
      @data_by_minute_result = get_chart_data_by_minute(coin_symbol, 100)
    end
  end

  def get_chart_data_by_minute(symbol, limit)
    data_by_minute = HTTParty.get("https://min-api.cryptocompare.com/data/histominute?fsym=#{symbol}&limit=#{limit}&tsym=BTC&aggregate=3&e=Bittrex&allData=true")
    data_by_minute_result = JSON.parse(data_by_minute.body)
    data_by_minute_result = data_by_minute_result["Data"]

    data_by_minute_result.each do |element|
      element["date"] = Time.at(element["time"]).to_s
    end
    return data_by_minute_result
  end
end

app/helpers/coins_helper.rb
module CoinsHelper

  def truncate_coin_name(string)
    if string.length > 15
      string[0..11]+"..."
    else
      string
    end
  end

end

app/views/coins/_carousel.html.erb
<div class="col s12 m12 l12">
  <div class="carousel carousel-slider center" data-indicators="true">
    <!-- <div class="carousel-fixed-item center">
      <a class="btn waves-effect blue white-text darken-text-2">button</a>
    </div> -->
    <% count = 0 %>
    <% @top_5_coins.each do |coin| %>
    <% ext = @cc_coin_list[coin.symbol] %>
      <% #if @top_5_cc_symbol[count] == "GBG"  %>
        <% #@top_5_cc_symbol[count] = "GOLOS" %>
      <div class="carousel-item black-text" href="<%= @carousel_position[count] %>">
        <div class="row">
          <div class="col s5 coin-logo" id="carousel-item<%= count %>">
            <% if ext != nil %>
            <img src="<%= ext[:image_url] %>" class="carousel-img">
            <% end %>
          </div>
          <div class="col s7 text-left">
            <h5>Biggest % Gain</h5>
            <% if ext != nil %>
            <h3><%= link_to "#{ ext[:full_name] }", "coins/#{coin.symbol}" %></h3>
            <% end %>
            <h5> <%= coin.pct_change %>%</h5>
            <h5>Last Price <%= coin.last_price %></h5>
            <h5>24hr Volume <%= coin.volume %> BTC</h5>
            <% count += 1 %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/coins/index.html.erb
<div class="container">
  <div class="row">
    <%= render "carousel" %>
  </div>
  <div class="row">
    <div class="col s12 m12 l12">
      <table data-sortable="false">
        <tr>
          <td colspan="4" style="border:none;">
            <h5>
              <strong>BITCOIN MARKETS</strong>
            </h5>
          </td>
          <td colspan="4" style="border:none;">
            <input type="text" id="filterInput" placeholder="Search coins...">
          </td>
        </tr>
      </table>
      <table class="striped highlight sortable-theme-bootstrap" id="coinsIndex" data-sortable>
        <thead>
          <tr>
            <th class="center" id="currency">Currency</th>
            <th class="hide-on-med-and-down text-center" id="market">Market</th>
            <th class="text-right" id="volume">Volume(BTC)</th>
            <th class="text-center" id="change">% Change</th>
            <th class="text-center" id="last">Last Price</th>
            <th class="text-center hide-on-med-and-down" id="high">24hr High</th>
            <th class="text-center hide-on-med-and-down" id="low">24hr Low</th>
            <th class="text-center hide-on-med-and-down" id="added">Added</th>
          </tr>
        </thead>
        <tbody>
          <% @coin_summary.each do |coin| %>
            <tr class="item">
              <td class="coin-title table-title">
                <a href="coins/<%= coin.symbol %>">
                  <% if @cc_coin_list[coin.symbol] != nil %>
                  <img src="<%= @cc_coin_list[coin.symbol][:image_url] %>" class="coin-image" title="<%= @cc_coin_list[coin.symbol][:full_name] %>">
                  <span style="font-size:1.5rem;"><%= @cc_coin_list[coin.symbol][:full_name] %></span>
                  <% end %>
                </a>
              </td>
              <td class="text-center hide-on-med-and-down coin-symbol table-data">
                BTC-<%= coin.symbol %>
              </td>
              <td class="text-right coin-volume table-data" data-value="<%= coin.volume %>">
                <%= coin.volume %>
              </td>
                <% if coin.prev_day > coin.last_price %>
                  <td class="text-right" data-value="<%= coin.pct_change %>">
                    <span class="red-text">
                      <i class="material-icons valign-wrapper red-text">arrow_drop_down</i>
                      <%= coin.pct_change %>
                      %
                    </span>
                  </td>
                <% elsif coin.prev_day < coin.last_price %>
                  <td class="text-right table-data" data-value="<%= coin.pct_change %>">
                    <span class="green-text">
                      <i class="material-icons valign-wrapper green-text">arrow_drop_up</i>
                      <%= coin.pct_change %>
                      %
                    </span>
                  </td>
                <% else %>
                  <td class="text-right table-data" data-value="<%= coin.pct_change %>">
                    <i class="material-icons valign-wrapper black-text">drag_handle</i>
                    <%= coin.pct_change %>
                    %
                  </td>
                <% end %>
                <td class="text-right coin-last table-data" data-value="<%= coin.last_price %>">
                  <%= coin.last_price %>
                </td>
                <td class="text-right hide-on-med-and-down table-data" data-value="<%= coin.high_24hr %>">
                  <%= coin.high_24hr %>
                </td>
                <td class="text-right hide-on-med-and-down table-data" data-value="<%= coin.low_24hr %>">
                  <%= coin.low_24hr %>
                </td>
                <td class="text-center hide-on-med-and-down table-data">
                  <%= coin.added %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/coins/show.html.erb
<%= javascript_include_tag "coins" %>

<!-- GRAPH -->
<div class="container row">
  <div class="col l7 m12 s12">
    <%= content_tag "div", id: "chartdiv", data: {chartArray: @data_by_minute_result, coinSymbol: @coin.symbol} do %>
  <% end %>
</div>

<!-- MAIN COIN INFO SECTION -->
<div class="col l5 m12 s12">
  <div class="row">
    <div class="col l6">
      <div class="head-info valign-wrapper">
        <h3 class="js-coin-symbol"><%= image_tag("#{@cc_coin_list[@coin.symbol][:image_url]}", size: "40x40", alt: "#{@coin.symbol}", class: "coin-img") %><%= @coin.symbol %></h3>
      </div>
    </div>
    <div class="col l4">
      <div class="head-info valign-wrapper">
        <!-- FOLLOW/UNFOLLOW BUTTON -->
        <div class="center-align">
          <a id="unfollow-coin" class="waves-effect waves-light btn red darken-4 <%= 'hide' if !@is_following %>" href="<%= following_path %>" data-method="delete" rel="nofollow">
            Unfollow
          </a>
          <a id="follow-coin" class="waves-effect waves-light btn green darken-4 <%= 'hide' if @is_following %>" href="<%= following_path %>" data-method="put" rel="nofollow">Follow
          </a>
        </div>
      </div>
    </div>

    <div class="col l2">
      <div id="alert-container" class="head-info valign-wrapper text-right">
        <!-- ALERT BUTTON-->
        <a id="alert-icon" class="btn btn-floating btn-medium cyan accent-4 waves-effect waves-light modal-trigger <%= 'hide' if !@is_following %>" href="#modal1" action="#modal1">
          <i class="material-icons left">add_alert</i>
        </a>
        <div id="modal1" class="modal  text-left">
          <div class="modal-content alert-form">
            <% if @is_following %>
              <%= render 'alerts/form1', alert: @alert, method: :post, remote: true%>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <table id="show-coin-table" class="bordered">
    <tbody class='coin-prices-table'>
      <tr>
        <!-- LAST -->
        <% if @coin.last_price < @coin.prev_day %>
          <td>
            <p class="coin-info red-text">LAST:</p>
          </td>
          <td>
            <p class="coin-info" data-field="Last">&#579;
              <%= @coin.last_price %></p>
          </td>
          <td class="text-center">
            <span class="red-text">
              <i class="material-icons valign-wrapper red-text">arrow_drop_down</i></span></td>
          <% elsif @coin.last_price > @coin.prev_day %>
            <td>
              <p class="coin-info green-text">LAST:</p>
            </td>
            <td>
              <p class="coin-info" data-field="Last">&#579;
                <%= @coin.last_price %></p>
            </td>
            <td class="coin-info text-center">
              <span class="green-text">
                <i class="material-icons valign-wrapper green-text">arrow_drop_up</i></span></td>
          <% else %>
            <td>
              <p class="coin-info">LAST:</p>
            </td>
            <td>
              <p class="coin-info" data-field="Last">&#579;
                <%= @coin.last_price %></p>
            </td>
            <td class="text-center">
              <span class="black-text">
                <i class="material-icons valign-wrapper black-text">drag_handle</i></span></td>
          <% end %>
        </tr>
        <tr>
          <!-- BASE VOL -->
          <td>
            <p class="coin-info">VOL:</p>
          </td>
          <td>
            <p class="coin-info" data-field="BaseVolume">&#579;
              <span><%= @coin.volume %></p>
            </td>
            <td></td>
          </tr>
          <tr>
            <!-- BID -->
            <td>
              <p class="coin-info">BID:</p>
            </td>
            <td>
              <p class="coin-info" data-field="Bid">&#579;
                <%= @coin.bid %></p>
            </td>
            <td></td>
          </tr>
          <tr>
            <!-- ASK -->
            <td>
              <p class="coin-info">ASK:</p>
            </td>
            <td>
              <p class="coin-info" data-field="Ask">&#579;
                <%= @coin.ask %></p>
            </td>
            <td></td>
          </tr>
          <tr>
            <!-- HIGH -->
            <td>
              <p class="coin-info">HIGH:</p>
            </td>
            <td>
              <p class="coin-info" data-field="High">&#579;
                <%= @coin.high_24hr %></p>
            </td>
            <td></td>
          </tr>
          <tr>
            <!-- LOW -->
            <td>
              <p class="coin-info">LOW:</p>
            </td>
            <td>
              <p class="coin-info" data-field="Low">&#579;
                <%= @coin.low_24hr %></p>
            </td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <!-- TIMESTAMP -->
      <p class="center-align" id="last-updated"></p>
    </div>
  </div>